### ISSUE TITLE
Add meta training module

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#100]
In order to incorporate meta-data we need to add modules to train the meta-data encoders. This issue should do the these  things.
- [x]  Add a file `meta_trainer.py` this file should include all things necessary to train an meta encoder module to generate meta embeddings. It should be able to be called from the command line as follow `python meta_trainer.py -p meta_config.json` 
- [x] Add sample auto encoder model to be trained 
- [x] Add unit to test JSON config files
