### ISSUE TITLE
Add meta-data fusion method and documentation

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#128]
Based on #100 we want to fuse meta-data with temporal data to enable better time series forecasts. 
- [x] Create a design document of meta-data fusion methods and explain relevant approaches 
- [x] Review design document with @kritim13 and other teammates. 
- [x] Implement agreed upon approach 
- [x] Create a JSON config file and appropriate unit tests. 
- [x] Test end to end in the Kaggle Notebook.

**Comment by isaacmg** [comment]
The design document is [located here](https://github.com/AIStream-Peelout/flow-forecast/wiki/Merging-Embeddings-with-Temporal-Data). I merged a PR last night that include partial support for fusion, however there is still a fair amount needed to actually get it working.

**Comment by isaacmg** [comment]
Update second PR was just merged and Kaggle notebook now has end-to-end example: https://www.kaggle.com/isaacmg/auto-encoder-forecasts)

**Comment by isaacmg** [comment]
Still need to run a full sweep to determine performance but I think V1 of this is mostly done.

**Comment by isaacmg** [comment]
This is now working in the second notebook too. However, I'm a little worried about issue #145. It is odd that the sweep is failing like it is currently.

**Comment by isaacmg** [comment]
Okay can confidently say this issue is done!
