### ISSUE TITLE
Add vector concatenation as a meta-data embedding method

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#146]
Now that we have meta-data fusing added. We may want to fuse representations using vector concatenation. 

Acceptance Criteria 
- [ ] Document in Wiki page regarding how vector concat works and possible shapes allowed. 
- [ ] Create a dictionary to handle different meta-data embedding classes.
- [ ] Vector concatenation can be passed as a meta-data embedding parameter in the standard config file. 
- [ ] This parameter should be tunable to time series input size, meta-data input size, and desired output size. 
- [ ] Raise error if the input dimensions are invalid
