### ISSUE TITLE
Incorporate lat/lon and gage meta data into forecast models

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#27]
Need a method of incorporating the static structured information into the model alongside the time series data. Specifically, lat and long should be incorporated in some way 
- [ ] Research and document methods in Wiki 
- [ ] Add methods to model
- [ ] Evaluate both with and without the static structured information

**Comment by isaacmg** [comment]
This essentially just a repeat of the meta-data issues #118
