### ISSUE TITLE
Complete meta-data

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#4]
Need to add stream flow data on missing values and flow ranges to the existing .json files. As usual this should include:
- [x] Save preliminary meta-data on GCS 
- [x] Add code for stream flow meta-data during the join. This should include the number of total missing values (for streamflow), streamflow elevation, streamflow slope (if available), and the range of cfs
- [ ] Passing test case on both dummy and real data for stream flow code
- [ ] Finalize meta-data during #3 and upload
